name: Publish to PyPI

on:
  release:
    types: [published] # ❗ بس لما تنشر Release من GitHub

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - run: uv build
      - run: uv publish
